"""Add product_type and sub_type to inventory_transactions

Revision ID: 4f7a84e004a4
Revises: 41ac630fb9b8
Create Date: 2025-07-08 08:31:37.503085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f7a84e004a4'
down_revision = '41ac630fb9b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_type', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('sub_type', sa.String(length=150), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_transactions', schema=None) as batch_op:
        batch_op.drop_column('sub_type')
        batch_op.drop_column('product_type')

    # ### end Alembic commands ###
