"""Initial migration for production

Revision ID: 5ef2680e358f
Revises: 
Create Date: 2025-07-08 08:44:19.007701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ef2680e358f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('contact_number', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('company_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=True),
    sa.Column('monogram_path', sa.String(length=200), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('contact_info', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conveyance_bills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bill_date', sa.Date(), nullable=False),
    sa.Column('person_name', sa.String(length=100), nullable=False),
    sa.Column('from_location', sa.String(length=200), nullable=True),
    sa.Column('to_location', sa.String(length=200), nullable=True),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_production',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('production_date', sa.Date(), nullable=False),
    sa.Column('machine_number', sa.String(length=50), nullable=False),
    sa.Column('design_number', sa.String(length=100), nullable=False),
    sa.Column('client_name', sa.String(length=150), nullable=True),
    sa.Column('total_production', sa.Float(), nullable=False),
    sa.Column('production_unit', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_type', sa.String(length=100), nullable=False),
    sa.Column('sub_type', sa.String(length=150), nullable=False),
    sa.Column('default_unit', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_type', 'sub_type', name='_product_subtype_uc')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('inventory_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('transaction_type', sa.String(length=10), nullable=False),
    sa.Column('inventory_item_id', sa.Integer(), nullable=False),
    sa.Column('product_type', sa.String(length=100), nullable=False),
    sa.Column('sub_type', sa.String(length=150), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=True),
    sa.Column('client_name', sa.String(length=150), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('fabrics_type', sa.String(length=100), nullable=True),
    sa.Column('design_code', sa.String(length=100), nullable=True),
    sa.Column('qty', sa.Float(), nullable=True),
    sa.Column('transaction_mode', sa.String(length=50), nullable=True),
    sa.Column('narration', sa.Text(), nullable=True),
    sa.Column('chq_no', sa.String(length=50), nullable=True),
    sa.Column('challan_voucher_no', sa.String(length=100), nullable=True),
    sa.Column('debit', sa.Float(), nullable=True),
    sa.Column('credit', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('inventory_transactions')
    op.drop_table('users')
    op.drop_table('inventory_items')
    op.drop_table('daily_production')
    op.drop_table('conveyance_bills')
    op.drop_table('company_details')
    op.drop_table('clients')
    # ### end Alembic commands ###
